CREATE TABLE IF NOT EXISTS refcode (
	refcodeID		INT(10)		NOT NULL AUTO_INCREMENT PRIMARY KEY,
	refcodeName		VARCHAR(255)	DEFAULT NULL,
	displayName		VARCHAR(255)	DEFAULT NULL,
	isDisabled		TINYINT(1)	NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reflink (
	reflinkID		INT(10)		NOT NULL AUTO_INCREMENT PRIMARY KEY,
	reflink			TEXT,
	reflinkTitle		TEXT,
	inputTime		INT(10)		NOT NULL DEFAULT 0,
	refcodeID		INT(10)
);

ALTER TABLE reflink ADD FOREIGN KEY (refcodeID) REFERENCES refcode (refcodeID) ON DELETE SET NULL;